### ISSUE TITLE
Question - documenting internals

### ISSUE THREAD

**Issue by ewbarnard** [php-fig-rectified/psr2r-sniffer#15]
@dereuromark - I'm considering documenting how this psr2r-sniffer works (internals documentation) in support of bringing people into one aspect of php internals (lexing/tokenizing; examining how PHP source is structured) - https://gist.github.com/ewbarnard/97ba2259f0e05e4331bbaa3394da4084

* develop vs master - it looks like I'm better off focusing on master rather than develop?
* docs/ vs wiki - I'd prefer to add to the source tree rather than the github wiki area. Correct?

Of course getting people to think about the POINT of this project is a plus. That's why I'd like to use this as a route to understanding how the Code Sniffer works, and how the sniffs consume tokens.

**Comment by dereuromark** [comment]
I think it needs to be first released as 1.0.0 stable.
For that it still needs some work.

I also consider at least changing {} positions to psr.
So the only thing remaining is the actual important part: The indentation.

This might make the migration path easier in general and creates less fuss.
