### ISSUE TITLE
Issue with alphabetical order of classes

### ISSUE THREAD

**Issue by orbex** [php-fig-rectified/psr2r-sniffer#20]
Weird behaviour occurs in sorting used classes in alphabetical order (see screenshot).
In my opinion a space comes before any letter...
![Alphabetical_order_classes](https://user-images.githubusercontent.com/2074126/81300042-719f6180-9077-11ea-899b-6bcdc588ec0a.png)

To fix the notice it wants me to place Ad **between** AdAdvertiser and AdGroupLeadgeneration.

Suspect sniff: PSR2R\Sniffs\Namespaces\UseInAlphabeticalOrderSniff.php
PHP: 7.3.9
IDE: PhpStorm 2020.1.1

**Comment by dereuromark** [comment]
This is true and some legacy issue of the sniffer ruleset.
If you can make a PR I am happy to merge it.

But it is fixed in the new https://github.com/php-fig-rectified/psr2r-sniffer/tree/php7 branch and the released 1.0.0-beta release (soon to be RC and stable).

**Comment by orbex** [comment]
Good news, looking forward to the official v1 release :)

**Comment by dereuromark** [comment]
Can you test it and let me know about issues?

**Comment by erikvanderschaaf** [comment]
Can confirm that the issue doesn't exist anymore in 1.0.0-beta
