### ISSUE TITLE
Uncaught Error: Class 'PHP_CodeSniffer\Runner' not found

### ISSUE THREAD

**Issue by eaxexe** [php-fig-rectified/psr2r-sniffer#27]
Hi there :)

I have psr2r-sniffer installed (in a CakePHP 4 project), via composer, running PHP 7.3.29.

When I run the sniffer, I get the following error:

```
PHP Fatal error:  Uncaught Error: Class 'PHP_CodeSniffer\Runner' not found in /home/sites/olive/htdocs/vendor/fig-r/psr2r-sniffer/PSR2R/Tools/Sniffer.php:73
Stack trace:
#0 /home/sites/olive/htdocs/vendor/fig-r/psr2r-sniffer/bin/sniff.php(23): PSR2R\Tools\Sniffer->sniff()
#1 {main}
  thrown in /home/sites/olive/htdocs/vendor/fig-r/psr2r-sniffer/PSR2R/Tools/Sniffer.php on line 73
```

I have PHP_CodeSniffer installed through composer as well, and can run `vendor/bin/phpcs path-to-file` without issues.

What could be wrong here? Thanks in advance!

**Comment by dereuromark** [comment]
That is weird, as this should not happen with normal execution.
You can see on my plugins that there is nothing special needed, it works fine.

How are you installing/using it?

**Comment by eaxexe** [comment]
> That is weird, as this should not happen with normal execution. You can see on my plugins that there is nothing special needed, it works fine.
> 
> How are you installing/using it?

Installation:
`composer require --dev fig-r/psr2r-sniffer`

Using:
`vendor/bin/sniff src/Controller/LoginController.php`

I am also rather confused yeah :)

**Comment by eaxexe** [comment]
@dereuromark :
I have just tried a completely clean CakePHP project, and get the same error.

Here are the commands I ran:

```
composer create-project --prefer-dist cakephp/app caketest
cd caketest
composer require --dev fig-r/psr2r-sniffer
vendor/bin/sniff src/Controller/PagesController.php
```

And got the exact same error.
This test was done on a different server than the first, just to see if that made a difference.

**Comment by dereuromark** [comment]
Specific php Version?

**Comment by dereuromark** [comment]
Oh that is the wrong command.
You should check how my plugins use it.

**Comment by eaxexe** [comment]
> Oh that is the wrong command. That file is not used and should probably get removed. You should check how my plugins use it.

Oh! Well that'd make sense then 😊 Though I just ran the command from the docs 😅
Where do I find your plugins, so I can check?

**Comment by dereuromark** [comment]
I see the readme uses and documents it still.

**Comment by dereuromark** [comment]
Example: https://github.com/dereuromark/cakephp-ide-helper

**Comment by eaxexe** [comment]
> Example: https://github.com/dereuromark/cakephp-ide-helper
> 
> Specifically https://github.com/dereuromark/cakephp-ide-helper/blob/b30bb2216858addb3c02d84e2719d723190b6189/composer.json#L74

That works perfectly, thanks so much! 😊

**Comment by dereuromark** [comment]
If u have time maybe u can help with fixing this command. Otherwise I will look into it these days.
It was just meant as syntactic sugar.

**Comment by dereuromark** [comment]
For now I fixed docs and removed the outdated file: https://github.com/php-fig-rectified/psr2r-sniffer/commit/b702ec97cade0d29ae6d71370c4dca63c7cac28a
