### ISSUE TITLE
Does not detect/fix indentation issues

### ISSUE THREAD

**Issue by blaaat** [php-fig-rectified/psr2r-sniffer#6]
This does not detect missing/too much indentation or space-usage instead of tabs.

**Comment by dereuromark** [comment]
Yes, that is a very complicated issue to fix, I doubt any of the current sniffers support this as of right now.

**Comment by blaaat** [comment]
PHP_CodeSniffer 2.7.0 is doing this (but with spaces)

**Comment by dereuromark** [comment]
Interesting, maybe this could be ported then.
