### ISSUE TITLE
Difference of SingleQuote sniff from Squiz.Strings.DoubleQuoteUsage

### ISSUE THREAD

**Issue by gmponos** [php-fig-rectified/psr2r-sniffer#8]
As the title says what's the difference between them?

**Comment by dereuromark** [comment]
If there is none, we can remove and use theirs.
But afaik theirs had a bug, not sure.

We definitely need some tests now with the new develop branch and sniffer v3.0.
Basic tests to ensure that it all works as expected.
Are you interested in helping out?
